services:
  - type: web
    name: workflowsaura-langflow
    env: python
    buildCommand: pip install -e ./src/backend/base
    startCommand: python -m uvicorn langflow.main:create_app --factory --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
